AllCops:
  TargetRubyVersion: 2.5

Layout/LineLength:
  Max: 120

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/activerecord-sqlserver-adapter.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes
